pipeline{
    agent any
    stages{
        stage('Init'){
            steps{
                echo "Hi this is Shashika From level 001"
                echo "We are strating the tesing"
            }
        }    
        stage('Build'){
            steps{
                echo "Building Sample Maven Project"
            }
        }
        stage('Deploy'){
            steps{
                echo 'Deploying in stagine Area' 
            }
        }
        stage('Deploy Production'){
            steps{
                echo 'Deploying in Production Area' 
            }
        }
        }
    }
